#!/bin/bash

MODE=$1

FLAGS=
CLEAN=

COLOR_WARN="\\033[0;33m"
COLOR_SUCCESS="\\033[1;32m"
COLOR_FAILURE="\\033[1;31m"
COLOR_NORMAL="\\033[0;39m"

STAGE=""

CC_LOC="CROSS_COMPILE=x86_64-linux-gnu-"
ARCH_LOC="x86_64"
LDFLAGS_LOC=""

print_error()
{
    echo -en "\n${COLOR_FAILURE} $1 ${COLOR_NORMAL}\r\n\n"
}

print_warn()
{
    echo -en "\n${COLOR_WARN} $1 ${COLOR_NORMAL}\r\n\n"
}

print_info()
{
    echo -en "\n${COLOR_SUCCESS} $1 ${COLOR_NORMAL}\r\n\n"
}

build_status_check()
{
    if [ $? -ne 0 ]; then
    print_error "transport for '$ARCH_LOC' build failed"
        exit 1;
    else
    print_info "transport for '$ARCH_LOC' build OK"
    fi;
}

check_mode()
{
case "$MODE" in
    "x86_64" | "host" | "x64")
        CC_LOC="CROSS_COMPILE=x86_64-linux-gnu-"
        ARCH_LOC="x86_64"
        LDFLAGS_LOC=""
        ;;

    "x86_64" | "host" | "x64")
        CC_LOC="CROSS_COMPILE=x86_64-linux-gnu-"
        ARCH_LOC="x86_64"
        LDFLAGS_LOC=""
        ;;
esac
}

check_clean_mode()
{
case "$PARAM" in
    "cleanall" )
        CLEAN="distclean"
    ;;
    "clean" )
        CLEAN="clean"
    ;;
esac
}

check_lib()
{
    LIB_DIR=.build/$ARCH_LOC/usr/local/lib

#    if [ ! -d $LIB_DIR ]; then
#        make $CC_LOC ARCH=$ARCH_LOC build_deps
#    else
        if  [ -e $LIB_DIR/$1 ]; then
            print_info "$2 for '$ARCH_LOC' is OK"
        else
            print_warn "$2 for '$ARCH_LOC' wasn't found. try to build"
            make $CC_LOC ARCH=$ARCH_LOC $3

            if  [ -e $LIB_DIR/$1 ]; then
                print_info "$2 for '$ARCH_LOC' successfully builded"
            else
                print_error "$2 for '$ARCH_LOC' wasn't found after build-attemnt!"
                exit 1
            fi;
        fi;
#    fi;
}

print_info "Mode: '$MODE'"

check_mode

for PARAM in $*; do
    check_clean_mode
done

if [ -n "$CLEAN" ]; then
    print_info "clearing"
    make $CLEAN $CC_LOC ARCH=$ARCH_LOC
fi;

check_lib libzmq.a ZMQ-lib build_zmq
make $CC_LOC ARCH=$ARCH_LOC

build_status_check

exit 0;
