/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: trike_cc_message.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C_NO_DEPRECATED
#define PROTOBUF_C_NO_DEPRECATED
#endif

#include "trike_cc_message.pb-c.h"
void   trike_ccmessage__init
                     (TrikeCCMessage         *message)
{
  static TrikeCCMessage init_value = TRIKE_CCMESSAGE__INIT;
  *message = init_value;
}
size_t trike_ccmessage__get_packed_size
                     (const TrikeCCMessage *message)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &trike_ccmessage__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t trike_ccmessage__pack
                     (const TrikeCCMessage *message,
                      uint8_t       *out)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &trike_ccmessage__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t trike_ccmessage__pack_to_buffer
                     (const TrikeCCMessage *message,
                      ProtobufCBuffer *buffer)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &trike_ccmessage__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
TrikeCCMessage *
       trike_ccmessage__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (TrikeCCMessage *)
     protobuf_c_message_unpack (&trike_ccmessage__descriptor,
                                allocator, len, data);
}
void   trike_ccmessage__free_unpacked
                     (TrikeCCMessage *message,
                      ProtobufCAllocator *allocator)
{
  PROTOBUF_C_ASSERT (message->base.descriptor == &trike_ccmessage__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor trike_ccmessage__field_descriptors[3] =
{
  {
    "dialog_id",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TrikeCCMessage, dialog_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "request_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TrikeCCMessage, request_id),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    PROTOBUF_C_OFFSETOF(TrikeCCMessage, data),
    NULL,
    NULL,
    0,            /* packed */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned trike_ccmessage__field_indices_by_name[] = {
  2,   /* field[2] = data */
  0,   /* field[0] = dialog_id */
  1,   /* field[1] = request_id */
};
static const ProtobufCIntRange trike_ccmessage__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor trike_ccmessage__descriptor =
{
  PROTOBUF_C_MESSAGE_DESCRIPTOR_MAGIC,
  "TrikeCCMessage",
  "TrikeCCMessage",
  "TrikeCCMessage",
  "",
  sizeof(TrikeCCMessage),
  3,
  trike_ccmessage__field_descriptors,
  trike_ccmessage__field_indices_by_name,
  1,  trike_ccmessage__number_ranges,
  (ProtobufCMessageInit) trike_ccmessage__init,
  NULL,NULL,NULL    /* reserved[123] */
};
