
all: rmall
#	gcc -g -O0 --no-omit-frame-pointer -Wall live.c -o live -lncurses
#	gcc -g -O0 --no-omit-frame-pointer -Wall colors.c -o colors -lncurses
#	gcc -g -O0 --no-omit-frame-pointer -Wall field.c -o field -lncurses
	gcc -g -O0 --no-omit-frame-pointer -Wall life_v1.c -o life_v1 -lncurses

rmall:
	rm -f live colors field