#!/bin/bash

MODE=$1

FLAGS=
CLEAN=
TRANSPORT=

COLOR_WARN="\\033[0;33m"
COLOR_SUCCESS="\\033[1;32m"
COLOR_FAILURE="\\033[1;31m"
COLOR_NORMAL="\\033[0;39m"

STAGE=""

print_error()
{
    echo -en "\n${COLOR_FAILURE} $1 ${COLOR_NORMAL}\r\n\n"
}

print_warn()
{
    echo -en "\n${COLOR_WARN} $1 ${COLOR_NORMAL}\r\n\n"
}

print_info()
{
    echo -en "\n${COLOR_SUCCESS} $1 ${COLOR_NORMAL}\r\n\n"
}

build_status_check()
{
    if [ $? -ne 0 ]; then
    print_error "$1 for '$ARCH_LOC' build failed"
        exit 1;
    else
    print_info "$1 for '$ARCH_LOC' build OK"
    fi;
}

check_mode()
{
case "$MODE" in
    "x86_64" | "host" | "x64")
        CC_LOC="CROSS_COMPILE=x86_64-linux-gnu-"
        ARCH_LOC="x86_64"
        LDFLAGS_LOC=""
        ;;
    "mv" | "smg1016m" | "smgm" | "1016m")
        CC_LOC="CROSS_COMPILE=arm-mv5sft-linux-gnueabi-"
        ARCH_LOC="mv"
        LDFLAGS_LOC="LDFLAGS=-DBOARD_SMG1016M"
        ;;
    "2016" | "smg2016" )
        CC_LOC="CROSS_COMPILE=arm-marvell-linux-gnueabi-"
        ARCH_LOC="2016"
        LDFLAGS_LOC="LDFLAGS=-DBOARD_2016"
        ;;
esac
}

check_clean_mode()
{
case "$PARAM" in
    "cleanall" )
        case "$TRANSPORT" in
            "pbyte" )
                CLEAN="clean_zmq distclean_pbyte"
                ;;
            "trike" )
                CLEAN="clean_deps distclean_trike"
                ;;
        esac
    ;;
    "clean" )
        case "$TRANSPORT" in
            "pbyte" )
                CLEAN="clean_pbyte"
                ;;
            "trike" )
                CLEAN="clean_trike"
                ;;
        esac
    ;;
esac
}

check_transport_mode()
{
case "$PARAM" in
    "pbyte" )
        TRANSPORT="pbyte"
        ;;
    "trike" )
        TRANSPORT="trike"
        ;;
    * )
esac
}

check_lib()
{
    LIB_DIR=.build/$ARCH_LOC/usr/local/lib

#    if [ ! -d $LIB_DIR ]; then
#        make $CC_LOC ARCH=$ARCH_LOC build_deps
#    else
        if  [ -e $LIB_DIR/$1 ]; then
            print_info "$2 for '$ARCH_LOC' is OK"
        else
            print_warn "$2 for '$ARCH_LOC' wasn't found. try to build"
            make $CC_LOC ARCH=$ARCH_LOC $3

            if  [ -e $LIB_DIR/$1 ]; then
                print_info "$2 for '$ARCH_LOC' successfully builded"
            else
                print_error "$2 for '$ARCH_LOC' wasn't found after build-attemnt!"
                exit 1
            fi;
        fi;
#    fi;
}

print_info "Mode: '$MODE'"

check_mode

for PARAM in $*; do
    check_transport_mode
done

if [ ! -n "$TRANSPORT" ]; then
    print_error "Transport not set!"
    echo "Usage: ./$0 <transport> <clean/cleanall>"
    exit 0
fi;

for PARAM in $*; do
    check_clean_mode
done

if [ -n "$CLEAN" ]; then
    print_info "clearing"
    make $CLEAN $CC_LOC ARCH=$ARCH_LOC
fi;

case "$TRANSPORT" in
    "pbyte" )
        check_lib libzmq.a ZMQ-lib build_zmq
        make $LDFLAGS_LOC $CC_LOC ARCH=$ARCH_LOC build_pbyte
        ;;
    "trike" )
        check_lib libzmq.a ZMQ-lib build_zmq
        check_lib libprotobuf.a protobuf-lib build_protobuf
        check_lib libprotobuf-c.a protobuf_c-lib build_protobuf_c
        make $LDFLAGS_LOC $CC_LOC ARCH=$ARCH_LOC build_trike
        ;;
esac

build_status_check "$TRANSPORT"

exit 0;
